
title: Escalante
version: 0.2.0

profiles:
  development:
    disqus_developer: true
    add_google_tracker: false
  staging:
    base_url: http://staging.escalante.io/
    add_google_tracker: false
    deploy:
      host: escalante.io
      path: /var/www/domains/escalante.io/staging/htdocs
  production:
    base_url: http://escalante.io/
    add_google_tracker: true
    deploy:
      host: escalante.io
      path: /var/www/domains/escalante.io/www/htdocs

disqus: escalante
google_analytics: UA-34212292-1
